const test=require('node:test');const assert=require('node:assert/strict');const p=require('./production-core');
const now='2026-10-21T06:10:00.000Z';
function context(){return {revision:now,date:'2026-10-21',slots:p.slots(now),night:{status:'complete',date:'2026-10-20'},mandatory_trade_ids:['t1'],trades:[{id:'t1'}],source_refs:['trade:t1','espn:1'],memory:[],player_events:[]};}
function draft(){return {schema:133,id:'daily-2026-10-21',date:'2026-10-21',kind:'daily',title:'Die erste Nacht der Saison',summary:'Die erste Bilanz.',source_revision:now,turns:Array.from({length:20},(_,i)=>({speaker:i%2?'tom':'michael',text:('Eine klare Einschätzung dieser Entwicklung braucht trotzdem etwas Geduld. ').repeat(4),source_refs:['trade:t1','espn:1']})),covered_trade_ids:['t1'],qa:{facts_checked:true,entertainment_checked:true,no_invented_quotes:true},opinions:[]};}
test('daily and extra weekly slots respect Berlin DST',()=>{assert.equal(p.slots('2026-10-25T23:30:00Z')[0].date,'2026-10-26');assert.equal(p.slots('2026-10-25T23:30:00Z').length,2);assert.equal(p.slots('2026-07-26T22:30:00Z')[0].date,'2026-07-27');});
test('valid two-host draft chunks under provider limit',()=>{let d=draft();assert.ok(p.validate(d,context(),now).words>=650);assert.equal(p.chunks(d.turns).flat().length,d.turns.length);for(const chunk of p.chunks(d.turns))assert.ok(chunk.reduce((n,t)=>n+t.text.length,0)<=1800);});
test('running NBA night or stale source prevents generation',()=>{let c=context();c.night.status='pending_games_or_boxscores';assert.throws(()=>p.validate(draft(),c,now),/NIGHT_NOT_FINAL/);assert.throws(()=>p.validate(draft(),context(),'2026-10-21T08:00:00Z'),/SOURCE_STALE/);});
test('trade must appear in spoken references, not only metadata',()=>{let d=draft();d.turns.forEach(t=>t.source_refs=['espn:1']);assert.throws(()=>p.validate(d,context(),now),/MANDATORY_TRADE_MISSING/);});
test('unapproved manager, FBA pronunciation and fabricated refs rejected',()=>{let d=draft();d.turns[0].speaker='maik';assert.throws(()=>p.validate(d,context(),now),/UNAPPROVED/);d=draft();d.turns[0].text+=' FBA';assert.throws(()=>p.validate(d,context(),now),/SPEECH_TEXT/);d=draft();d.turns[0].source_refs=['made-up'];assert.throws(()=>p.validate(d,context(),now),/UNKNOWN_SOURCE/);});
test('publication requires full audio, current night, all new trades and 08:00',()=>{let j={status:'audio_ready',date:'2026-10-21',kind:'daily',night_date:'2026-10-20',covered_trade_ids:['t1'],audio:{file_id:'id',seconds:400}};assert.deepEqual(p.canPublish(j,context(),now),[]);assert.ok(p.canPublish(j,context(),'2026-10-21T05:59:00Z').includes('BEFORE_RELEASE'));let c=context();c.mandatory_trade_ids.push('t2');assert.ok(p.canPublish(j,c,now).includes('NEW_MANDATORY_TRADE'));j.audio.seconds=90;assert.ok(p.canPublish(j,context(),now).includes('AUDIO_DURATION'));});
test('MP3 frame parser measures and concatenates valid streams, rejects truncation',()=>{let frame=Array(417).fill(0);frame.splice(0,4,255,251,144,0);let a=p.mp3(frame.concat(frame));assert.equal(a.frames,2);assert.equal(a.bytes.length,834);assert.ok(a.seconds>0);assert.throws(()=>p.mp3(frame.slice(0,100)),/TRUNCATED/);});
