const test=require('node:test');const assert=require('node:assert/strict');const p=require('./production-core');
const now='2026-10-21T06:10:00.000Z';
function previewFixture(){let c=context(),d=draft();c.night.status='out_of_season';c.mandatory_trade_ids=[];c.trades=[];c.bbm={status:'ready',as_of:now};c.published=[];c.source_refs=['espn:league:'+now,'bbm:profile:'+now];d.covered_trade_ids=[];d.turns.forEach(t=>t.source_refs=c.source_refs);d.editorial_plan={mode:'preview',topic_key:'lions-offensive-risk',angle:'Wie belastbar ist die offensive Kaderstrategie der Lions?'};return {c,d};}
test('verified preseason analysis is allowed without a new transaction',()=>{let {c,d}=previewFixture();assert.ok(p.validate(d,c,now).words>=650);delete d.editorial_plan;assert.throws(()=>p.validate(d,c,now),/NO_NEW_VERIFIED_STORY/);});
test('preview rejects repeated angles, stale BBM and missing analysis sources',()=>{let {c,d}=previewFixture();c.published=[{editorial_plan:{topic_key:d.editorial_plan.topic_key}}];assert.throws(()=>p.validate(d,c,now),/ALREADY_COVERED/);c.published=[];c.bbm.as_of='2026-10-18T06:10:00Z';assert.throws(()=>p.validate(d,c,now),/ANALYSIS_STALE/);c.bbm.as_of=now;d.turns.forEach(t=>t.source_refs=[c.source_refs[0]]);assert.throws(()=>p.validate(d,c,now),/SOURCES_REQUIRED/);});
test('preview never bypasses unfinished games or weekly completion',()=>{let {c,d}=previewFixture();c.night.status='pending_games_or_boxscores';assert.throws(()=>p.validate(d,c,now),/NIGHT_NOT_FINAL/);c.night.status='complete';assert.throws(()=>p.validate(d,c,now),/PREVIEW_NOT_APPLICABLE/);});
function context(){return {revision:now,date:'2026-10-21',slots:p.slots(now),night:{status:'complete',date:'2026-10-20'},mandatory_trade_ids:['t1'],trades:[{id:'t1'}],source_refs:['trade:t1','espn:1'],memory:[],player_events:[]};}
function draft(){return {schema:133,id:'daily-2026-10-21',date:'2026-10-21',kind:'daily',title:'Die erste Nacht der Saison',summary:'Die erste Bilanz.',source_revision:now,turns:Array.from({length:20},(_,i)=>({speaker:i%2?'tom':'michael',text:('Eine klare Einschätzung dieser Entwicklung braucht trotzdem etwas Geduld. ').repeat(4),source_refs:['trade:t1','espn:1']})),covered_trade_ids:['t1'],qa:{facts_checked:true,entertainment_checked:true,no_invented_quotes:true},opinions:[]};}
test('daily and extra weekly slots respect Berlin DST',()=>{assert.equal(p.slots('2026-10-25T23:30:00Z')[0].date,'2026-10-26');assert.equal(p.slots('2026-10-25T23:30:00Z').length,2);assert.equal(p.slots('2026-07-26T22:30:00Z')[0].date,'2026-07-27');});
test('valid two-host draft chunks under provider limit',()=>{let d=draft();assert.ok(p.validate(d,context(),now).words>=650);assert.equal(p.chunks(d.turns).flat().length,d.turns.length);for(const chunk of p.chunks(d.turns))assert.ok(chunk.reduce((n,t)=>n+t.text.length,0)<=1800);});
test('running NBA night or stale source prevents generation',()=>{let c=context();c.night.status='pending_games_or_boxscores';assert.throws(()=>p.validate(draft(),c,now),/NIGHT_NOT_FINAL/);assert.throws(()=>p.validate(draft(),context(),'2026-10-21T08:00:00Z'),/SOURCE_STALE/);});
test('trade must appear in spoken references, not only metadata',()=>{let d=draft();d.turns.forEach(t=>t.source_refs=['espn:1']);assert.throws(()=>p.validate(d,context(),now),/MANDATORY_TRADE_MISSING/);});
test('unapproved manager, FBA pronunciation and fabricated refs rejected',()=>{let d=draft();d.turns[0].speaker='maik';assert.throws(()=>p.validate(d,context(),now),/UNAPPROVED/);d=draft();d.turns[0].text+=' FBA';assert.throws(()=>p.validate(d,context(),now),/SPEECH_TEXT/);d=draft();d.turns[0].source_refs=['made-up'];assert.throws(()=>p.validate(d,context(),now),/UNKNOWN_SOURCE/);});
test('publication requires full audio, current night, all new trades and 08:00',()=>{let j={status:'audio_ready',date:'2026-10-21',kind:'daily',night_date:'2026-10-20',covered_trade_ids:['t1'],audio:{file_id:'id',seconds:400}};assert.deepEqual(p.canPublish(j,context(),now),[]);assert.ok(p.canPublish(j,context(),'2026-10-21T05:59:00Z').includes('BEFORE_RELEASE'));let c=context();c.mandatory_trade_ids.push('t2');assert.ok(p.canPublish(j,c,now).includes('NEW_MANDATORY_TRADE'));j.audio.seconds=90;assert.ok(p.canPublish(j,context(),now).includes('AUDIO_DURATION'));});
test('MP3 frame parser measures and concatenates valid streams, rejects truncation',()=>{let frame=Array(417).fill(0);frame.splice(0,4,255,251,144,0);let a=p.mp3(frame.concat(frame));assert.equal(a.frames,2);assert.equal(a.bytes.length,834);assert.ok(a.seconds>0);assert.throws(()=>p.mp3(frame.slice(0,100)),/TRUNCATED/);});

function managerFixture(){let c=context(),d=draft();c.manager_speakers=[{speaker:'manager_chris'}];d.turns[0].text+=' Willkommen zur fiktiven Pressekonferenz.';d.turns.splice(1,0,{speaker:'manager_chris',kind:'fictional_press_conference',text:'Mein Kader hat keine Schwächen. Nur Kategorien, die ich aus ästhetischen Gründen ignoriere.',source_refs:[]});d.summary+=' Mit fiktiver KI-Pressekonferenz.';d.qa={facts_checked:true,entertainment_checked:true,no_unlabeled_invented_quotes:true,fiction_clearly_labeled:true,fiction_excluded_from_facts:true};return {c,d};}
test('registered consented manager fiction accepted, host-only remains compatible',()=>{let {c,d}=managerFixture();assert.ok(p.validate(d,c,now));assert.ok(p.validate(draft(),context(),now));});
test('manager fiction needs spoken label, metadata and correct kind',()=>{for(const change of [d=>d.turns[0].text='Eine echte Pressekonferenz.',d=>delete d.turns[1].kind,d=>d.summary='Ohne Kennzeichnung.',d=>delete d.qa.fiction_excluded_from_facts]){let {c,d}=managerFixture();change(d);assert.throws(()=>p.validate(d,c,now),/FICTION/);}});
test('manager fiction cannot carry a factual trade reference or monopolize episode',()=>{let {c,d}=managerFixture();d.turns[1].source_refs=['trade:t1'];assert.throws(()=>p.validate(d,c,now),/FICTION_NOT_FACT/);({c,d}=managerFixture());d.turns.forEach(t=>t.source_refs=[]);assert.throws(()=>p.validate(d,c,now),/MANDATORY_TRADE_MISSING/);({c,d}=managerFixture());d.turns[1].text='Wort '.repeat(46);assert.throws(()=>p.validate(d,c,now),/MANAGER_TOO_LONG/);({c,d}=managerFixture());d.turns.splice(2,0,d.turns[1]);assert.throws(()=>p.validate(d,c,now),/MANAGER_DUPLICATE/);});
function claimFixture(){let c=context(),d=draft();c.teams=[{id:1}];d.host_claims=[{key:'lions-risk',host:'michael',claim:'Die Lions bleiben eine riskante Wette.',quote:'Eine klare Einschätzung dieser Entwicklung',condition:'Falls der Kader gesund bleibt.',horizon:'Saison 2026/27',team_ids:[1],turn_index:0}];return {c,d};}
test('claims preserve owner, spoken excerpt, conditions and source turn',()=>{let {c,d}=claimFixture();assert.ok(p.validate(d,c,now));d.host_claims[0].host='tom';assert.throws(()=>p.validate(d,c,now),/HOST_CLAIM_SPEAKER/);d.host_claims[0].host='michael';d.host_claims[0].quote='Niemals gesagte Behauptung';assert.throws(()=>p.validate(d,c,now),/HOST_CLAIM_TEXT/);});
test('season memory retains claims older than 35 episodes and excludes unpublished/fiction',()=>{let {d}=claimFixture();let jobs=Array.from({length:65},(_,i)=>({...d,id:'episode-'+i,date:'2026-10-21',status:'published',season:2027}));jobs.push({...d,id:'not-published',status:'audio_ready'});let fiction=JSON.parse(JSON.stringify(d));fiction.id='fiction';fiction.status='published';fiction.turns[0].speaker='manager_chris';jobs.push(fiction);let m=p.hostMemory(jobs);assert.equal(m.length,65);assert.ok(m.some(x=>x.id==='episode-0:lions-risk'));assert.ok(m.every(x=>x.host==='michael'&&x.condition==='Falls der Kader gesund bleibt.'));});
test('claim reviews append without rewriting original, need current factual evidence',()=>{let {c,d}=claimFixture();let old={...d,id:'daily-2026-10-20',date:'2026-10-20',status:'published'};c.host_memory=p.hostMemory([old]);let id=c.host_memory[0].id,ref='memory:claim:'+id;c.source_refs.push(ref);d.turns[0].source_refs.push(ref);d.memory_reviews=[{claim_id:id,status:'challenged',assessment:'Die aktuelle Entwicklung widerspricht der damaligen These.',turn_index:0}];assert.ok(p.validate(d,c,now));let memories=p.hostMemory([old,{...d,status:'published'}]);assert.equal(memories[0].status,'challenged');assert.equal(memories[0].claim,old.host_claims[0].claim);assert.equal(memories[0].reviews.length,1);d.turns[0].source_refs=[ref];assert.throws(()=>p.validate(d,c,now),/MEMORY_REVIEW_EVIDENCE/);});
test('voice routing has no fallback, freezes manager identity before paid calls',()=>{const fs=require('node:fs'),vm=require('node:vm'),sandbox={};vm.runInNewContext(fs.readFileSync(require.resolve('./production-gas.js'),'utf8'),sandbox);let cfg={michael:'voice-m',tom:'voice-t',managers:{manager_chris:{voice_id:'voice-c',consent_confirmed_at:'2026-09-30'}}},j={turns:[{speaker:'michael'},{speaker:'tom'},{speaker:'manager_chris',kind:'fictional_press_conference'}]};assert.equal(JSON.stringify(sandbox.prodVoices136_(j,cfg)),JSON.stringify({michael:'voice-m',tom:'voice-t',manager_chris:'voice-c'}));j.turns[2].speaker='manager_unknown';assert.throws(()=>sandbox.prodVoices136_(j,cfg),/MANAGER_VOICE_NOT_APPROVED/);});
