/* Install beside v132. Rendering uses only separately configured host IDs and key.
 * Public routes expose published episodes only. Private analysis never leaves Sheets.
 */
var FBA_PROD133={context:'FBA_Podcast_Redaktion_v133',inbox:'FBA_Podcast_Inbox_v133',jobs:'FBA_Podcast_Produktion_v133',status:'FBA_Podcast_Status_v133',chunk:20000};
function prodSheet133_(name,headers){var s=book().getSheetByName(name);if(!s){s=book().insertSheet(name);if(headers){s.getRange(1,1,1,headers.length).setValues([headers]).setFontWeight('bold');s.setFrozenRows(1);}s.hideSheet();}return s;}
function prodConfig133_(){var p=espnPropertiesV1_();return {enabled:p.getProperty('FBA_PODCAST_AUTO_ENABLED')==='true',key:p.getProperty('ELEVENLABS_API_KEY')||'',michael:p.getProperty('FBA_VOICE_MICHAEL')||'',tom:p.getProperty('FBA_VOICE_TOM')||'',approved:p.getProperty('FBA_HOSTS_APPROVED')==='true'};}
function prodMissing133_(c){var missing=[];if(!c.key)missing.push('ELEVENLABS_API_KEY');if(!c.michael)missing.push('FBA_VOICE_MICHAEL');if(!c.tom)missing.push('FBA_VOICE_TOM');if(!c.approved)missing.push('FBA_HOSTS_APPROVED');if(c.michael&&c.michael===c.tom)missing.push('TWO_DIFFERENT_VOICES');return missing;}
function prodState133_(state,detail){var sh=prodSheet133_(FBA_PROD133.status,['key','value']);var cfg=prodConfig133_();sh.getRange(2,1,7,2).setValues([['state',state],['detail',detail||''],['updated_at',new Date().toISOString()],['missing',prodMissing133_(cfg).join(', ')],['auto_enabled',cfg.enabled],['daily','08:00 Europe/Berlin; 5–10 Minuten'],['weekly','Montag ab 08:00 Europe/Berlin; ca. 20 Minuten']]);}
function prodJobs133_(){var sh=prodSheet133_(FBA_PROD133.jobs,['episode_id','status','updated_at','state_1','state_2','state_3','state_4','state_5','state_6','state_7','state_8']);if(sh.getLastRow()<2)return [];return sh.getRange(2,1,sh.getLastRow()-1,11).getValues().map(function(r){try{return JSON.parse(r.slice(3).join(''));}catch(e){throw Error('JOB_STATE_CORRUPT');}});}
function prodSave133_(j){var sh=prodSheet133_(FBA_PROD133.jobs),ids=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,1).getValues().map(function(r){return r[0];}):[],idx=ids.indexOf(j.id),row=idx<0?sh.getLastRow()+1:idx+2;var s=JSON.stringify(j);if(s.length>160000)throw Error('JOB_TOO_LARGE');var values=[j.id,j.status,new Date().toISOString()];for(var k=0;k<8;k++)values.push(s.substr(k*20000,20000));sh.getRange(row,1,1,11).setNumberFormat('@').setValues([values]);SpreadsheetApp.flush();}
function prodContext133_(){var p=podcastRead132_(),published=prodJobs133_().filter(function(j){return j.status==='published';});return FBA_PRODUCTION133.context(p,published,new Date().toISOString());}
function prepareFbaPodcast133(){var lock=LockService.getUserLock();if(!lock.tryLock(1000))return {busy:true};try{
 var c=prodContext133_(),sh=prodSheet133_(FBA_PROD133.context),old={};try{old=JSON.parse(sh.getRange(1,1).getValue()||'{}');}catch(e){}
 if(old.revision===c.revision&&old.date===c.date)return c;
 var slot=old.slot===0?1:0,text=JSON.stringify(c),count=Math.ceil(text.length/20000);if(count>100)throw Error('CONTEXT_TOO_LARGE');
 sh.getRange(2+slot*100,1,count,1).setNumberFormat('@').setValues(Array.from({length:count},function(_,i){return ['J'+text.substr(i*20000,20000)];}));SpreadsheetApp.flush();
 sh.getRange(1,1).setNumberFormat('@').setValue(JSON.stringify({schema:133,slot:slot,start_row:2+slot*100,count:count,revision:c.revision,date:c.date}));
 return c;
 }finally{lock.releaseLock();}}
function prodAccept133_(c){var sh=prodSheet133_(FBA_PROD133.inbox,['payload_chunks','request_id','count','state']);var head=sh.getRange(2,2,1,3).getValues()[0],request=String(head[0]||'');if(!request||String(head[2]).indexOf('ACCEPTED:')===0||String(head[2]).indexOf('REJECTED:')===0)return;
 if(head[2]!=='SUBMITTED:'+request)return;var count=Number(head[1]);if(!Number.isInteger(count)||count<1||count>10)throw Error('INBOX_COUNT');
 var raw=sh.getRange(2,1,count,1).getValues().map(function(r){if(typeof r[0]!=='string'||r[0][0]!=='J')throw Error('INBOX_CHUNK');return r[0].slice(1);}).join('');
 try{var payload=JSON.parse(raw);if(payload.schema!==133||payload.request_id!==request||!Array.isArray(payload.episodes)||payload.episodes.length<1||payload.episodes.length>2)throw Error('INBOX_SCHEMA');
   var jobs=prodJobs133_(),ids={};payload.episodes.forEach(function(d){if(ids[d.id])throw Error('DUPLICATE_SLOT');ids[d.id]=true;FBA_PRODUCTION133.validate(d,c,new Date().toISOString());var old=jobs.find(function(j){return j.id===d.id;});if(old&&old.draft_hash!==stableHashV36_(JSON.stringify(d)))throw Error('EPISODE_EXISTS');});
   payload.episodes.forEach(function(d){if(jobs.some(function(j){return j.id===d.id;}))return;var stats=FBA_PRODUCTION133.validate(d,c,new Date().toISOString());var j=JSON.parse(JSON.stringify(d));j.draft_hash=stableHashV36_(JSON.stringify(d));j.status='queued';j.accepted_at=new Date().toISOString();j.night_date=c.night.date;j.stats=stats;j.parts=FBA_PRODUCTION133.chunks(d.turns).map(function(turns){return {turns:turns,status:'queued'};});prodSave133_(j);});
   sh.getRange(2,4).setValue('ACCEPTED:'+request);
 }catch(e){sh.getRange(2,4).setValue('REJECTED:'+request+':'+String(e.message).slice(0,160));throw e;}}
function prodEleven133_(path,c,options){options=options||{};options.headers={'xi-api-key':c.key};options.muteHttpExceptions=true;return UrlFetchApp.fetch('https://api.elevenlabs.io'+path,options);}
function prodBudget133_(c,chars){var r=prodEleven133_('/v1/user/subscription',c);if(r.getResponseCode()!==200)throw Error('ELEVENLABS_ACCOUNT_CHECK_FAILED');var p=JSON.parse(r.getContentText());var count=Number(p.character_count),limit=Number(p.character_limit);if(!Number.isFinite(count)||!Number.isFinite(limit)||limit-count<chars*2+2000)throw Error('CREDIT_RESERVE_REACHED');return {remaining:limit-count};}
function prodDrive133_(path,options){options=options||{};options.headers={Authorization:'Bearer '+ScriptApp.getOAuthToken()};options.muteHttpExceptions=true;var r=UrlFetchApp.fetch('https://www.googleapis.com'+path,options);if(r.getResponseCode()<200||r.getResponseCode()>299){var reason='';try{var err=JSON.parse(r.getContentText()).error;reason=(err.errors||[]).map(function(x){return x.reason;}).join(',')||err.status||'';}catch(ignore){}throw Error('PODCAST_STORAGE_HTTP_'+r.getResponseCode()+':'+reason);}return r;}
function prodFolder133_(){var props=espnPropertiesV1_(),id=props.getProperty('FBA_PODCAST_AUDIO_FOLDER_ID');if(id)return id;var r=prodDrive133_('/drive/v3/files?fields=id',{method:'post',contentType:'application/json',payload:JSON.stringify({name:'FBA Podcast – Produktion',mimeType:'application/vnd.google-apps.folder'})});id=JSON.parse(r.getContentText()).id;props.setProperty('FBA_PODCAST_AUDIO_FOLDER_ID',id);return id;}
function prodUpload133_(name,bytes,folder){var boundary='fba133_'+Utilities.getUuid().replace(/-/g,''),meta={name:name,mimeType:'audio/mpeg',parents:[folder]},prefix='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: audio/mpeg\r\n\r\n';
 var body=Utilities.newBlob(prefix).getBytes().concat(bytes,Utilities.newBlob('\r\n--'+boundary+'--').getBytes());return JSON.parse(prodDrive133_('/upload/drive/v3/files?uploadType=multipart&fields=id,size',{method:'post',contentType:'multipart/related; boundary='+boundary,payload:body}).getContentText());}
function prodRenderPart133_(j,c){var i=j.parts.findIndex(function(p){return p.status!=='ready';});if(i<0)return false;var part=j.parts[i];if(part.status==='requesting')throw Error('PAID_REQUEST_UNCERTAIN');
 var chars=part.turns.reduce(function(n,t){return n+t.text.length;},0);prodBudget133_(c,chars);
 var inputs=part.turns.map(function(t){return {text:t.text,voice_id:t.speaker==='michael'?c.michael:c.tom};}),payload={model_id:'eleven_v3',language_code:'de',inputs:inputs};
 var prev=j.parts.slice(Math.max(0,i-3),i).map(function(p){return p.request_id;}).filter(Boolean);if(prev.length)payload.previous_request_ids=prev;if(i+1<j.parts.length)payload.future_text=j.parts[i+1].turns[0].text.slice(0,100);
 part.status='requesting';j.status='rendering';j.voices=j.voices||{michael:c.michael,tom:c.tom};if(j.voices.michael!==c.michael||j.voices.tom!==c.tom)throw Error('HOST_CHANGED_DURING_EPISODE');prodSave133_(j);
 var r=prodEleven133_('/v1/text-to-dialogue?output_format=mp3_44100_128',c,{method:'post',contentType:'application/json',payload:JSON.stringify(payload)}),code=r.getResponseCode();
 if(code===429){part.status='queued';j.status='queued';prodSave133_(j);throw Error('ELEVENLABS_RATE_LIMIT');}if(code!==200)throw Error('ELEVENLABS_RENDER_HTTP_'+code);
 var parsed=FBA_PRODUCTION133.mp3(r.getBlob().getBytes());if(parsed.seconds<2)throw Error('AUDIO_TOO_SHORT');var file=prodUpload133_(j.id+'-part-'+i+'.mp3',parsed.bytes,prodFolder133_());
 var headers=r.getAllHeaders();part.status='ready';part.file_id=file.id;part.seconds=parsed.seconds;part.request_id=headers['request-id']||headers['Request-Id']||headers['x-request-id']||null;prodSave133_(j);return true;}
function prodAssemble133_(j){var bytes=[],seconds=0;j.parts.forEach(function(p){if(p.status!=='ready')throw Error('PART_NOT_READY');var r=prodDrive133_('/drive/v3/files/'+encodeURIComponent(p.file_id)+'?alt=media');var parsed=FBA_PRODUCTION133.mp3(r.getBlob().getBytes());bytes=bytes.concat(parsed.bytes);seconds+=parsed.seconds;});
 var file=prodUpload133_('FBA-Funk-'+j.id+'.mp3',bytes,prodFolder133_());j.audio={file_id:file.id,seconds:seconds,bytes:bytes.length};j.status='audio_ready';prodSave133_(j);}
function prodPublish133_(j,c){var errors=FBA_PRODUCTION133.canPublish(j,c,new Date().toISOString());if(errors.length){if(errors.length===1&&errors[0]==='BEFORE_RELEASE')return;throw Error(errors.join(','));}
 // Only this newly generated, validated final file becomes public; folder and chunks stay private.
 prodDrive133_('/drive/v3/files/'+encodeURIComponent(j.audio.file_id)+'/permissions',{method:'post',contentType:'application/json',payload:JSON.stringify({type:'anyone',role:'reader',allowFileDiscovery:false})});
 var perms=JSON.parse(prodDrive133_('/drive/v3/files/'+encodeURIComponent(j.audio.file_id)+'/permissions?fields=permissions(type,role)').getContentText());if(!(perms.permissions||[]).some(function(p){return p.type==='anyone'&&p.role==='reader';}))throw Error('AUDIO_PUBLICATION_UNVERIFIED');
 j.status='published';j.published_at=new Date().toISOString();prodSave133_(j);prodState133_('PUBLISHED',j.id);}
function runFbaPodcast133(force){var hour=Number(Utilities.formatDate(new Date(),'Europe/Berlin','H'));if(force!==true&&(hour<7||hour>13))return;var props=espnPropertiesV1_(),lock=LockService.getScriptLock();if(!lock.tryLock(1000))return;var now=Date.now(),lease=Number(props.getProperty('FBA_PODCAST133_LEASE')||0);if(lease>now){lock.releaseLock();return;}props.setProperty('FBA_PODCAST133_LEASE',String(now+7*60000));lock.releaseLock();
 try{var c=prepareFbaPodcast133();if(!c||c.busy)return;prodAccept133_(c);var cfg=prodConfig133_(),missing=prodMissing133_(cfg);if(missing.length){prodState133_('SETUP_REQUIRED',missing.join(', '));return;}if(!cfg.enabled){prodState133_('PAUSED','Automatische Vertonung noch nicht aktiviert.');return;}
 var jobs=prodJobs133_(),j=jobs.find(function(x){return x.date===c.date&&['queued','rendering','audio_ready'].includes(x.status);});if(!j){prodState133_('WAITING_FOR_EDITORIAL','Keine neue freigegebene Folge.');return;}
 if(j.status!=='audio_ready'){if(j.source_revision!==c.revision&&Date.now()-Date.parse(j.accepted_at)>6*3600000)throw Error('DRAFT_EXPIRED');prodBudget133_(cfg,j.parts.filter(function(p){return p.status!=='ready';}).reduce(function(n,p){return n+p.turns.reduce(function(m,t){return m+t.text.length;},0);},0));
   while(Date.now()-now<200000&&prodRenderPart133_(j,cfg)){}
   if(j.parts.every(function(p){return p.status==='ready';}))prodAssemble133_(j);
 }if(j.status==='audio_ready')prodPublish133_(j,prodContext133_());else prodState133_('RENDERING',j.id);
 }catch(e){var message=String(e.message||e).slice(0,200);prodState133_('BLOCKED',message);console.error('FBA Podcast: '+message);}finally{props.deleteProperty('FBA_PODCAST133_LEASE');}}
function installFbaPodcast133(){prodSheet133_(FBA_PROD133.inbox,['payload_chunks','request_id','count','state']);prodJobs133_();prepareFbaPodcast133();if(!ScriptApp.getProjectTriggers().some(function(t){return t.getHandlerFunction()==='runFbaPodcast133';}))ScriptApp.newTrigger('runFbaPodcast133').timeBased().everyMinutes(5).create();prodState133_('SETUP_REQUIRED',prodMissing133_(prodConfig133_()).join(', '));runFbaPodcast133(true);return verifyFbaPodcast133();}
function verifyFbaPodcast133(){var cfg=prodConfig133_(),jobs=prodJobs133_(),result={schema:133,worker_installed:ScriptApp.getProjectTriggers().some(function(t){return t.getHandlerFunction()==='runFbaPodcast133';}),auto_enabled:cfg.enabled,missing:prodMissing133_(cfg),episodes:jobs.map(function(j){return {id:j.id,status:j.status};}),sources_ready:!!podcastRead132_(),editorial_context_ready:!!book().getSheetByName(FBA_PROD133.context)};Logger.log(JSON.stringify(result));return result;}
function activateFbaPodcast133(){var c=prodConfig133_();if(prodMissing133_(c).length)throw Error('SETUP_REQUIRED');prodBudget133_(c,1000);['michael','tom'].forEach(function(k){var r=prodEleven133_('/v1/voices/'+encodeURIComponent(c[k]),c);if(r.getResponseCode()!==200)throw Error('VOICE_NOT_AVAILABLE_'+k);});prodFolder133_();espnPropertiesV1_().setProperty('FBA_PODCAST_AUTO_ENABLED','true');runFbaPodcast133();return verifyFbaPodcast133();}
function fbaPodcastFeed133_(p){var eps=prodJobs133_().filter(function(j){return j.status==='published';}).reverse().map(function(j){return {id:j.id,kind:j.kind,title:j.title,summary:j.summary,published_at:j.published_at,duration_seconds:Math.round(j.audio.seconds),preview_url:'https://drive.google.com/file/d/'+j.audio.file_id+'/preview',audio_url:'https://drive.google.com/uc?export=download&id='+j.audio.file_id};});return monsterJsonResponseV29_({ok:true,schema:133,episodes:eps},p.callback||'');}
function verifyFbaPodcastStorage133(){var id=prodFolder133_(),meta=JSON.parse(prodDrive133_('/drive/v3/files/'+encodeURIComponent(id)+'?fields=id,mimeType,capabilities(canAddChildren,canShare)').getContentText());if(meta.mimeType!=='application/vnd.google-apps.folder'||!meta.capabilities||!meta.capabilities.canAddChildren||!meta.capabilities.canShare)throw Error('AUDIO_FOLDER_NOT_WRITABLE');var result={ok:true,storage:'private_production_folder',writable:true,can_share_final_audio:true};Logger.log(JSON.stringify(result));return result;}
